#! /bin/sh

set -e

ln -sf /usr/share/madsonic/madsonic.sh /usr/bin/madsonic

chmod 750 /var/madsonic

# Clear jetty cache.
rm -rf /var/madsonic/jetty

# Configure Madsonic service.
update-rc.d madsonic defaults 99

# Start Madsonic service.
invoke-rc.d madsonic start
